# Generated by Django 4.2 on 2025-03-14 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tutorials.auto_fill


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='uploads/cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), tutorials.auto_fill.validate_file_size])),
                ('structured_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.JSONField(default=dict)),
                ('key_skills', models.TextField(blank=True)),
                ('technical_skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('interest', models.TextField(blank=True)),
                ('fit_for_role', models.TextField(blank=True)),
                ('aspirations', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
