# Generated by Django 5.1.4 on 2025-03-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvapplication',
            name='structured_experience_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvapplication',
            name='structured_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvapplication',
            name='structured_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvapplication',
            name='structured_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
