# Generated by Django 5.0.1 on 2025-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
