# Generated by Django 4.2 on 2025-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.PositiveIntegerField(blank=True, help_text='Salary offered for the job.', null=True),
        ),
    ]
