# Generated by Django 4.2 on 2025-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcv',
            name='file',
            field=models.FileField(upload_to='uploaded_cvs/'),
        ),
        migrations.AlterField(
            model_name='uploadedcv',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
