# Generated by Django 5.0.1 on 2025-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='child_company_name',
            field=models.CharField(blank=True, help_text='Child or subsidiary company name, if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_documents',
            field=models.TextField(blank=True, help_text='Documents required for application.', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], help_text='Type of work (e.g., remote, hybrid, on-site).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='preferred_skills',
            field=models.TextField(blank=True, help_text='List of preferred skills for the job (comma-separated).', null=True),
        ),
    ]
