# Generated by Django 5.1.5 on 2025-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, help_text="Optional: Enter the company's location (up to 100 characters).", max_length=100, null=True),
        ),
    ]
