# Generated by Django 5.1.4 on 2025-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_cvapplication_structured_experience_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_industry',
            field=models.ManyToManyField(blank=True, to='tutorials.industry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_location',
            field=models.ManyToManyField(blank=True, to='tutorials.location'),
        ),
    ]
