# Generated by Django 4.2 on 2025-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='unique_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
