# Generated by Django 4.2 on 2025-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_jobapplication_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
