# Generated by Django 4.2.20 on 2025-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_uploadedcv_file_alter_uploadedcv_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcv',
            name='file',
            field=models.FileField(upload_to='uploads/raw_cvs/'),
        ),
        migrations.AlterField(
            model_name='uploadedcv',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
