# Generated by Django 5.1.4 on 2025-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_industry_location_customuser_user_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_industry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_location',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_industry',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_location',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
