# Generated by Django 4.2 on 2025-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_cvapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercv',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usercv',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
