# Generated by Django 4.2 on 2025-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_company_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, help_text="Optional: Enter the company's location (up to 100 characters).", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
