# Generated by Django 5.1.5 on 2025-02-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
