# Generated by Django 4.2 on 2025-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_cvapplication_right_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvapplication',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cvapplication',
            name='preferred_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cvapplication',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cvapplication',
            name='willingness_to_relocate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cvapplication',
            name='work_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cvapplication',
            name='work_start_date',
            field=models.DateField(null=True),
        ),
    ]
