# Generated by Django 5.1.4 on 2025-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
